# Generated by Django 3.2.7 on 2022-05-04 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_trade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Average price',
                'verbose_name_plural': 'Average price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Investition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_trade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investition_buys', to='app_trade.trade', verbose_name='Buy trade')),
                ('sell_trade', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investition_sells', to='app_trade.trade', verbose_name='Sell trade')),
            ],
        ),
    ]
