# Generated by Django 3.2.7 on 2022-05-04 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_symbol', models.CharField(max_length=32, verbose_name='Market symbol')),
            ],
            options={
                'ordering': ('market_symbol',),
            },
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quote', models.DecimalField(blank=True, decimal_places=8, max_digits=23, null=True, verbose_name='Current quote')),
                ('base_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pair_bases', to='app_trade.asset', verbose_name='Base asset')),
                ('second_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pair_seconds', to='app_trade.asset', verbose_name='Second asset')),
            ],
            options={
                'ordering': ('base_asset', 'second_asset'),
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(verbose_name='Date of making transaction')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('price', models.DecimalField(decimal_places=20, max_digits=32, verbose_name='Price of asset')),
                ('amount', models.DecimalField(decimal_places=20, max_digits=32, verbose_name='Amount of asset')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='app_trade.pair', verbose_name='Pair')),
            ],
        ),
    ]
